In [2]:
# augmentation testing

import numpy as np
from copy import deepcopy

arrays = [np.random.rand(50, 50) for i in range(5)]
cntArrays = [deepcopy(arrays[i]) for i in range(5)]

In [3]:
# testing rotation - direction (n-1, n) is equal to merging and rotating

newArray = np.array(arrays)
x = len(newArray.shape)
rot90 = np.rot90(newArray)

cnt = [np.rot90(cntArrays[i]) for i in range(5)]
rot90cnt = np.array(cnt)


In [4]:
x

3

In [5]:
print(np.array_equal(rot90, rot90cnt))


False


In [6]:
m = np.array([[1,2],[3,4]], int)

m

array([[1, 2],
       [3, 4]])

In [7]:
print(np.rot90(m))
print("------------------")
print(np.rot90(m, 2))

[[2 4]
 [1 3]]
------------------
[[4 3]
 [2 1]]


In [8]:
m = np.arange(8).reshape((2,2,2))

print(m)
print("------------")

np.rot90(m, 1, (1, 2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
------------


array([[[1, 3],
        [0, 2]],

       [[5, 7],
        [4, 6]]])

In [30]:
# testing flipping - flipud will always flip along the 0th axis so it is different
# fliplr will work the same. the matter is to use flip() and manually set axes (count from the end).
flipArray = np.array(arrays)

verticalFlip = np.flip(flipArray, -1)

flipCnt = [np.flip(cntArrays[i], -1) for i in range(5)]
np.array(flipCnt)

np.array_equal(verticalFlip, flipCnt)

True

In [28]:
m = np.arange(12).reshape((2, 3, 2, 2))
np.flip(m, -2)

array([[[ 2,  3],
        [ 0,  1]],

       [[ 6,  7],
        [ 4,  5]],

       [[10, 11],
        [ 8,  9]]])

In [25]:
# translation testing - works fine

def translate(tx, ty, image):
    _, N, M = image.shape
    image_translated = np.zeros_like(image)
    image_translated[:, max(tx,0):M+min(tx,0), max(ty,0):N+min(ty,0)] = image[:, -min(tx,0):M-max(tx,0), -min(ty,0):N-max(ty,0)]
    return image_translated

img = np.arange(32).reshape((2, 4, 4))
translate(-1, 0, img)

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [ 0,  0,  0,  0]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [ 0,  0,  0,  0]]])